DROP TABLE IF EXISTS url;
CREATE TABLE url (original_url VARCHAR(255) PRIMARY KEY UNIQUE NOT NULL, shorten_hash VARCHAR(5) UNIQUE NOT NULL);
/*CREATE TABLE url (original_url VARCHAR(255) PRIMARY KEY UNIQUE NOT NULL, shorten_hash VARCHAR(5) UNIQUE NOT NULL, expiration_time DATETIME NOT NULL);*/
